import { FieldModel } from './field.model';

export class OptionsModel {
  constructor() {
    this.classes = '';
    this.sortClass = '';
    this.height = '';
    this.undefinedText = '暂无数据';
    // 条纹
    this.striped = false;
    // sortName = '';
    this.sortOrder = '';
    this.sortStable = false;
    this.iconsPrefix = '';
    this.iconSize = '';
    this.buttonsClass = '';
    this.dataField = '';
    this.totalField = '';
    this.ajax = '';
    this.method = 'POST';
    this.url = '';
    this.cache = false;
    this.contentType = '';
    this.dataType = '';
    this.ajaxOptions = '';
    this.queryParams = '';
    this.queryParamsType = '';
    // responseHandler: any;
    this.pagination = true;
    this.paginationLoop = false;
    this.onlyInfoPagination = false;
    this.sidePagination = 'server';
    this.pageNumber = 1;
    this.pageSize = 50;
    this.pageList = '[10, 25, 50, 100]';
    this.selectItemName = '';
    this.smartDisplay = false;
    this.escape = false;
    this.search = false;
    this.searchOnEnterKey = false;
    this.strictSearch = false;
    this.searchText = '';
    this.searchTimeOut = 0;
    this.trimOnSearch = 0;
    this.showHeader = false;
    this.showFooter = false;
    this.showColumns = false;
    this.showRefresh = false;
    this.showToggle = false;
    this.showPaginationSwitch = false;
    this.minimumCountColumns = 0;
    this.idField = '';
    this.version = '';
    this.editView = false;
    this.uniqueId = '';
    this.cardView = false;
    this.detailView = false;
    // detailFormatter: any;
    this.searchAlign = '';
    this.buttonsAlign = '';
    this.toolbarAlign = '';
    this.paginationVAlign = '';
    this.paginationHAlign = '';
    this.paginationDetailHAlign = '';
    this.paginationPreText = '';
    this.paginationNextText = '';
    this.clickToSelect = false;
    this.singleSelect = false;
    this.toolbar = '';
    this.checkboxHeader = false;
    this.maintainSelected = false;
    this.sortable = false;
    this.silentSort = false;
    this.locale = '';
    this.showExport = false;
    this.exportDataType = 'basic'; // export data type, support:  'basic', 'all', 'selected'.
    this.autoload = true;
  }

  classes: string;
  sortClass: string;
  height: string;
  undefinedText: string;
  // 条纹
  striped: boolean;
  // sortName: string;
  sortOrder: string;
  sortStable: boolean;
  iconsPrefix: string;
  iconSize: string;
  buttonsClass: string;
  // icons: any;
  // data: Array<any>;
  dataField: string;
  totalField: string;
  ajax: any;
  method: string;
  url: string;
  cache: boolean;
  contentType: string;
  dataType: string;
  ajaxOptions: any;
  queryParams: any;
  queryParamsType: string;
  // responseHandler: any;
  pagination: boolean;
  paginationLoop: boolean;
  onlyInfoPagination: boolean;
  sidePagination: string;
  pageNumber: number;
  pageSize: number;
  pageList: String;
  selectItemName: string;
  smartDisplay: boolean;
  escape: boolean;
  search: boolean;
  searchOnEnterKey: boolean;
  strictSearch: boolean;
  searchText: string;
  searchTimeOut: number;
  trimOnSearch: number;
  showHeader: boolean;
  showFooter: boolean;
  showColumns: boolean;
  showRefresh: boolean;
  showToggle: boolean;
  showPaginationSwitch: boolean;
  minimumCountColumns: number;
  idField: string;
  version: string;
  editView: boolean;
  uniqueId: string;
  cardView: boolean;
  detailView: boolean;
  // detailFormatter: any;
  searchAlign: string;
  buttonsAlign: string;
  toolbarAlign: string;
  paginationVAlign: string;
  paginationHAlign: string;
  paginationDetailHAlign: string;
  paginationPreText: string;
  paginationNextText: string;
  clickToSelect: boolean;
  singleSelect: boolean;
  toolbar: string;
  checkboxHeader: boolean;
  maintainSelected: boolean;
  sortable: boolean;
  silentSort: boolean;
  // rowStyle: any;
  // rowAttributes: any;
  // customSearch: any;
  // customSort: any;
  locale: string;
  // footerStyle: any;
  showExport: boolean;
  exportDataType: string; // export data type, support:  'basic', 'all', 'selected'.
  autoload: boolean;
}
